### ISSUE TITLE
Issue storing groups values

### ISSUE THREAD

**Issue by KrishnaAgrawal5** [rabwill/generic-target-audience#9]
Hi,

Thanks a lot for this project.
I am facing an issue where the values in the people picker field of the property pane are not getting stored after I publish it to the page.
Any help is highly appreciated.

Thanks

**Comment by KrishnaAgrawal5** [comment]
Issue resolved. 
I was initializing the variable to empty array in oninit method which was causing the problem.

**Comment by rabwill** [comment]
Well done @KrishnaAgrawal5 👏🏽
